In [1]:
# Import the necessary libraries
import pandas as pd
import sqlite3
from sqlalchemy import create_engine, func
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.orm import Session
Base = declarative_base()

In [2]:
df = pd.read_csv("clean_data.csv")
engine = create_engine("sqlite:///housing.db")
df.to_sql('mytable', engine, if_exists='replace', index=False)

In [3]:
Base.metadata.create_all(engine)
session = Session(bind=engine)
session

In [4]:
class Housing(Base):
    __tablename__ = "mytable"
    ID = Column(Integer, primary_key=True)
    ADDRESS = Column(String)
    SUBURB = Column(String)
    PRICE = Column(Integer)
    LAND_AREA = Column(Integer)
    CBD_DIST = Column(Integer)
    NEAREST_STN = Column(String)
    DATE_SOLD = Column(String)
    POSTCODE = Column(String)
    LATITUDE = Column(Float)
    LONGITUDE = Column(Float)
    NEAREST_SCH = Column(Integer)

In [5]:
perth_housing = session.query(Housing)
results = session.query(Housing.PRICE, Housing.DATE_SOLD).all()
results

[(1600000, '01-2011'),
 (1451000, '01-2011'),
 (1315000, '01-2011'),
 (1050000, '01-2011'),
 (1050000, '01-2011'),
 (930000, '01-2011'),
 (870000, '01-2011'),
 (835000, '01-2011'),
 (820000, '01-2011'),
 (820000, '01-2011'),
 (730000, '01-2011'),
 (725000, '01-2011'),
 (620000, '01-2011'),
 (605000, '01-2011'),
 (555000, '01-2011'),
 (500000, '01-2011'),
 (495000, '01-2011'),
 (450000, '01-2011'),
 (439000, '01-2011'),
 (420000, '01-2011'),
 (415000, '01-2011'),
 (400000, '01-2011'),
 (375000, '01-2011'),
 (335000, '01-2011'),
 (315000, '01-2011'),
 (1220000, '01-2012'),
 (1200000, '01-2012'),
 (895000, '01-2012'),
 (880000, '01-2012'),
 (860000, '01-2012'),
 (840000, '01-2012'),
 (815000, '01-2012'),
 (810000, '01-2012'),
 (735000, '01-2012'),
 (720000, '01-2012'),
 (690000, '01-2012'),
 (685000, '01-2012'),
 (679000, '01-2012'),
 (671000, '01-2012'),
 (645000, '01-2012'),
 (645000, '01-2012'),
 (640000, '01-2012'),
 (630000, '01-2012'),
 (625000, '01-2012'),
 (610000, '01-2012'),
 (569900, '01-2012'),
 (540000, '01-2012'),
 (499000, '01-2012'),
 (484000, '01-2012'),
 (480000, '01-2012'),
 (455000, '01-2012'),
 (447000, '01-2012'),
 (445000, '01-2012'),
 (440000, '01-2012'),
 (415000, '01-2012'),
 (405000, '01-2012'),
 (390000, '01-2012'),
 (375000, '01-2012'),
 (375000, '01-2012'),
 (335000, '01-2012'),
 (331000, '01-2012'),
 (280000, '01-2012'),
 (255000, '01-2012'),
 (215000, '01-2012'),
 (2365000, '01-2013'),
 (1565000, '01-2013'),
 (1450000, '01-2013'),
 (1350000, '01-2013'),
 (1250000, '01-2013'),
 (1250000, '01-2013'),
 (1180000, '01-2013'),
 (1150000, '01-2013'),
 (1110000, '01-2013'),
 (1030000, '01-2013'),
 (1002000, '01-2013'),
 (937000, '01-2013'),
 (930000, '01-2013'),
 (910000, '01-2013'),
 (905000, '01-2013'),
 (880000, '01-2013'),
 (870000, '01-2013'),
 (870000, '01-2013'),
 (860000, '01-2013'),
 (855000, '01-2013'),
 (850000, '01-2013'),
 (825000, '01-2013'),
 (816000, '01-2013'),
 (805000, '01-2013'),
 (790000, '01-2013'),
 (790000, '01-2013'),
 (765000, '01-2013'),
 (740000, '01-2013'),
 (730000, '01-2013'),
 (720000, '01-2013'),
 (715000, '01-2013'),
 (705000, '01-2013'),
 (690000, '01-2013'),
 (686000, '01-2013'),
 (684000, '01-2013'),
 (675000, '01-2013'),
 (610000, '01-2013'),
 (607500, '01-2013'),
 (600000, '01-2013'),
 (599000, '01-2013'),
 (595000, '01-2013'),
 (595000, '01-2013'),
 (582000, '01-2013'),
 (580000, '01-2013'),
 (575000, '01-2013'),
 (570000, '01-2013'),
 (560000, '01-2013'),
 (555000, '01-2013'),
 (538000, '01-2013'),
 (520000, '01-2013'),
 (495000, '01-2013'),
 (487000, '01-2013'),
 (475000, '01-2013'),
 (460000, '01-2013'),
 (455000, '01-2013'),
 (450000, '01-2013'),
 (445000, '01-2013'),
 (439000, '01-2013'),
 (430000, '01-2013'),
 (420000, '01-2013'),
 (412000, '01-2013'),
 (400000, '01-2013'),
 (380000, '01-2013'),
 (375000, '01-2013'),
 (372000, '01-2013'),
 (370000, '01-2013'),
 (365000, '01-2013'),
 (350000, '01-2013'),
 (346000, '01-2013'),
 (325000, '01-2013'),
 (315000, '01-2013'),
 (310000, '01-2013'),
 (295000, '01-2013'),
 (279000, '01-2013'),
 (272000, '01-2013'),
 (260000, '01-2013'),
 (260000, '01-2013'),
 (252500, '01-2013'),
 (179000, '01-2013'),
 (125000, '01-2013'),
 (2010000, '01-2014'),
 (1800000, '01-2014'),
 (1625000, '01-2014'),
 (1320000, '01-2014'),
 (1280000, '01-2014'),
 (1210000, '01-2014'),
 (1200000, '01-2014'),
 (1160000, '01-2014'),
 (1150000, '01-2014'),
 (1040000, '01-2014'),
 (1000000, '01-2014'),
 (980000, '01-2014'),
 (886000, '01-2014'),
 (885000, '01-2014'),
 (880000, '01-2014'),
 (872000, '01-2014'),
 (862500, '01-2014'),
 (860000, '01-2014'),
 (850000, '01-2014'),
 (850000, '01-2014'),
 (830000, '01-2014'),
 (810000, '01-2014'),
 (800000, '01-2014'),
 (780000, '01-2014'),
 (760000, '01-2014'),
 (750000, '01-2014'),
 (725000, '01-2014'),
 (725000, '01-2014'),
 (717500, '01-2014'),
 (702500, '01-2014'),
 (695000, '01-2014'),
 (670000, '01-2014'),
 (665000, '01-2014'),
 (660000, '01-2014'),
 (655000, '01-2014'),
 (630000, '01-2014'),
 (625000, '01-2014'),
 (610000, '01-2014'),
 (600000, '01-2014'),
 (592000, '01-2014'),
 (590000, '01-2014'),
 (567000, '01-2014'),
 (565000, '01-2014'),
 (555000, '01-2014'),
 (555000, '01-2014'),
 (550000, '01-2014'),
 (549000, '01-2014'),
 (540000, '01-2014'),
 (538000, '01-2014'),
 (530000, '01-2014'),
 (530000, '01-2014'),
 (515000, '01-2014'),
 (515000, '01-2014'),
 (515000, '01-2014'),
 (500000, '01-2014'),
 (499000, '01-2014'),
 (480000, '01-2014'),
 (475000, '01-2014'),
 (475000, '01-2014'),
 (470000, '01-2014'),
 (459000, '01-2014'),
 (450000, '01-2014'),
 (450000, '01-2014'),
 (450000, '01-2014'),
 (446000, '01-2014'),
 (440000, '01-2014'),
 (439000, '01-2014'),
 (430000, '01-2014'),
 (425000, '01-2014'),
 (420000, '01-2014'),
 (420000, '01-2014'),
 (420000, '01-2014'),
 (415000, '01-2014'),
 (405000, '01-2014'),
 (400000, '01-2014'),
 (400000, '01-2014'),
 (395000, '01-2014'),
 (385000, '01-2014'),
 (380000, '01-2014'),
 (376000, '01-2014'),
 (375000, '01-2014'),
 (372000, '01-2014'),
 (342000, '01-2014'),
 (341250, '01-2014'),
 (340000, '01-2014'),
 (330000, '01-2014'),
 (329000, '01-2014'),
 (325000, '01-2014'),
 (310000, '01-2014'),
 (305000, '01-2014'),
 (300000, '01-2014'),
 (270000, '01-2014'),
 (259000, '01-2014'),
 (255000, '01-2014'),
 (247000, '01-2014'),
 (210000, '01-2014'),
 (190000, '01-2014'),
 (154000, '01-2014'),
 (129000, '01-2014'),
 (51000, '01-2014'),
 (1900000, '01-2015'),
 (1850000, '01-2015'),
 (1710000, '01-2015'),
 (1700000, '01-2015'),
 (1450000, '01-2015'),
 (1410000, '01-2015'),
 (1310000, '01-2015'),
 (1300000, '01-2015'),
 (1250000, '01-2015'),
 (1250000, '01-2015'),
 (1150000, '01-2015'),
 (1150000, '01-2015'),
 (1135000, '01-2015'),
 (1120000, '01-2015'),
 (1110000, '01-2015'),
 (1110000, '01-2015'),
 (1100000, '01-2015'),
 (1070000, '01-2015'),
 (1065000, '01-2015'),
 (1060000, '01-2015'),
 (1050000, '01-2015'),
 (1040000, '01-2015'),
 (1040000, '01-2015'),
 (1035000, '01-2015'),
 (1020000, '01-2015'),
 (1000000, '01-2015'),
 (1000000, '01-2015'),
 (980000, '01-2015'),
 (952500, '01-2015'),
 (940000, '01-2015'),
 (900000, '01-2015'),
 (875000, '01-2015'),
 (875000, '01-2015'),
 (865000, '01-2015'),
 (855000, '01-2015'),
 (850000, '01-2015'),
 (842500, '01-2015'),
 (835000, '01-2015'),
 (810000, '01-2015'),
 (795000, '01-2015'),
 (795000, '01-2015'),
 (790000, '01-2015'),
 (785000, '01-2015'),
 (785000, '01-2015'),
 (770000, '01-2015'),
 (765000, '01-2015'),
 (758000, '01-2015'),
 (750000, '01-2015'),
 (745000, '01-2015'),
 (720000, '01-2015'),
 (716000, '01-2015'),
 (710000, '01-2015'),
 (695000, '01-2015'),
 (690000, '01-2015'),
 (685000, '01-2015'),
 (685000, '01-2015'),
 (670000, '01-2015'),
 (665000, '01-2015'),
 (655000, '01-2015'),
 (655000, '01-2015'),
 (650000, '01-2015'),
 (650000, '01-2015'),
 (645000, '01-2015'),
 (640000, '01-2015'),
 (620000, '01-2015'),
 (620000, '01-2015'),
 (618000, '01-2015'),
 (615000, '01-2015'),
 (606240, '01-2015'),
 (605000, '01-2015'),
 (600000, '01-2015'),
 (595000, '01-2015'),
 (592500, '01-2015'),
 (590000, '01-2015'),
 (590000, '01-2015'),
 (589000, '01-2015'),
 (588000, '01-2015'),
 (585000, '01-2015'),
 (585000, '01-2015'),
 (584000, '01-2015'),
 (582000, '01-2015'),
 (580000, '01-2015'),
 (570000, '01-2015'),
 (567500, '01-2015'),
 (567000, '01-2015'),
 (565000, '01-2015'),
 (560000, '01-2015'),
 (550000, '01-2015'),
 (550000, '01-2015'),
 (549000, '01-2015'),
 (543000, '01-2015'),
 (530000, '01-2015'),
 (530000, '01-2015'),
 (525000, '01-2015'),
 (522500, '01-2015'),
 (520000, '01-2015'),
 (520000, '01-2015'),
 (520000, '01-2015'),
 (520000, '01-2015'),
 (515000, '01-2015'),
 (515000, '01-2015'),
 (500000, '01-2015'),
 (500000, '01-2015'),
 (500000, '01-2015'),
 (499000, '01-2015'),
 (499000, '01-2015'),
 (495000, '01-2015'),
 (490000, '01-2015'),
 (488000, '01-2015'),
 (484000, '01-2015'),
 (480900, '01-2015'),
 (480000, '01-2015'),
 (480000, '01-2015'),
 (480000, '01-2015'),
 (480000, '01-2015'),
 (475000, '01-2015'),
 (475000, '01-2015'),
 (470000, '01-2015'),
 (470000, '01-2015'),
 (467000, '01-2015'),
 (465000, '01-2015'),
 (465000, '01-2015'),
 (465000, '01-2015'),
 (460000, '01-2015'),
 (460000, '01-2015'),
 (455000, '01-2015'),
 (452500, '01-2015'),
 (450000, '01-2015'),
 (450000, '01-2015'),
 (450000, '01-2015'),
 (440000, '01-2015'),
 (440000, '01-2015'),
 (432000, '01-2015'),
 (430000, '01-2015'),
 (430000, '01-2015'),
 (430000, '01-2015'),
 (429000, '01-2015'),
 (425000, '01-2015'),
 (421000, '01-2015'),
 (420000, '01-2015'),
 (420000, '01-2015'),
 (420000, '01-2015'),
 (418000, '01-2015'),
 (415000, '01-2015'),
 (415000, '01-2015'),
 (415000, '01-2015'),
 (411000, '01-2015'),
 (410000, '01-2015'),
 (405000, '01-2015'),
 (405000, '01-2015'),
 (400000, '01-2015'),
 (400000, '01-2015'),
 (400000, '01-2015'),
 (400000, '01-2015'),
 (399000, '01-2015'),
 (395000, '01-2015'),
 (395000, '01-2015'),
 (390000, '01-2015'),
 (390000, '01-2015'),
 (388000, '01-2015'),
 (388000, '01-2015'),
 (385000, '01-2015'),
 (380000, '01-2015'),
 (380000, '01-2015'),
 (370000, '01-2015'),
 (367500, '01-2015'),
 (360000, '01-2015'),
 (355000, '01-2015'),
 (351500, '01-2015'),
 (340000, '01-2015'),
 (340000, '01-2015'),
 (330000, '01-2015'),
 (330000, '01-2015'),
 (330000, '01-2015'),
 (325000, '01-2015'),
 (320000, '01-2015'),
 (320000, '01-2015'),
 (317500, '01-2015'),
 (315000, '01-2015'),
 (310000, '01-2015'),
 (307000, '01-2015'),
 (295000, '01-2015'),
 (290000, '01-2015'),
 (285500, '01-2015'),
 (285000, '01-2015'),
 (275000, '01-2015'),
 (260000, '01-2015'),
 (245000, '01-2015'),
 (240000, '01-2015'),
 (2360000, '01-2016'),
 (2250000, '01-2016'),
 (1800000, '01-2016'),
 (1700000, '01-2016'),
 (1600000, '01-2016'),
 (1550000, '01-2016'),
 (1548000, '01-2016'),
 (1485000, '01-2016'),
 (1400000, '01-2016'),
 (1385000, '01-2016'),
 (1335000, '01-2016'),
 (1335000, '01-2016'),
 (1300000, '01-2016'),
 (1285000, '01-2016'),
 (1270000, '01-2016'),
 (1200000, '01-2016'),
 (1200000, '01-2016'),
 (1200000, '01-2016'),
 (1200000, '01-2016'),
 (1150000, '01-2016'),
 (1150000, '01-2016'),
 (1150000, '01-2016'),
 (1100000, '01-2016'),
 (1035000, '01-2016'),
 (1000000, '01-2016'),
 (980000, '01-2016'),
 (980000, '01-2016'),
 (960000, '01-2016'),
 (940000, '01-2016'),
 (915000, '01-2016'),
 (900000, '01-2016'),
 (895000, '01-2016'),
 (894000, '01-2016'),
 (885000, '01-2016'),
 (864000, '01-2016'),
 (860000, '01-2016'),
 (850000, '01-2016'),
 (850000, '01-2016'),
 (845000, '01-2016'),
 (835000, '01-2016'),
 (832000, '01-2016'),
 (825000, '01-2016'),
 (780000, '01-2016'),
 (775000, '01-2016'),
 (760000, '01-2016'),
 (755000, '01-2016'),
 (736500, '01-2016'),
 (720000, '01-2016'),
 (710000, '01-2016'),
 (702000, '01-2016'),
 (700000, '01-2016'),
 (700000, '01-2016'),
 (699000, '01-2016'),
 (697500, '01-2016'),
 (695000, '01-2016'),
 (695000, '01-2016'),
 (693000, '01-2016'),
 (691500, '01-2016'),
 (690000, '01-2016'),
 (689000, '01-2016'),
 (680000, '01-2016'),
 (675000, '01-2016'),
 (670000, '01-2016'),
 (665000, '01-2016'),
 (660000, '01-2016'),
 (655000, '01-2016'),
 (655000, '01-2016'),
 (650000, '01-2016'),
 (650000, '01-2016'),
 (647000, '01-2016'),
 (647000, '01-2016'),
 (637000, '01-2016'),
 (625000, '01-2016'),
 (610000, '01-2016'),
 (602000, '01-2016'),
 (595000, '01-2016'),
 (593000, '01-2016'),
 (580000, '01-2016'),
 (575000, '01-2016'),
 (575000, '01-2016'),
 (570000, '01-2016'),
 (567000, '01-2016'),
 (565000, '01-2016'),
 (560000, '01-2016'),
 (558000, '01-2016'),
 (557500, '01-2016'),
 (555000, '01-2016'),
 (555000, '01-2016'),
 (550000, '01-2016'),
 (547500, '01-2016'),
 (545000, '01-2016'),
 (536000, '01-2016'),
 (535000, '01-2016'),
 (530000, '01-2016'),
 (530000, '01-2016'),
 (525000, '01-2016'),
 (525000, '01-2016'),
 (520000, '01-2016'),
 (520000, '01-2016'),
 (520000, '01-2016'),
 (520000, '01-2016'),
 (515000, '01-2016'),
 (515000, '01-2016'),
 (515000, '01-2016'),
 (515000, '01-2016'),
 (512350, '01-2016'),
 (510000, '01-2016'),
 (510000, '01-2016'),
 (510000, '01-2016'),
 (502000, '01-2016'),
 (500000, '01-2016'),
 (497000, '01-2016'),
 (495000, '01-2016'),
 (495000, '01-2016'),
 (495000, '01-2016'),
 (490000, '01-2016'),
 (490000, '01-2016'),
 (490000, '01-2016'),
 (490000, '01-2016'),
 (490000, '01-2016'),
 (485000, '01-2016'),
 (484000, '01-2016'),
 (480000, '01-2016'),
 (480000, '01-2016'),
 (479000, '01-2016'),
 (475000, '01-2016'),
 (475000, '01-2016'),
 (473500, '01-2016'),
 (472000, '01-2016'),
 (470000, '01-2016'),
 (470000, '01-2016'),
 (466000, '01-2016'),
 (465000, '01-2016'),
 (465000, '01-2016'),
 (465000, '01-2016'),
 (465000, '01-2016'),
 (465000, '01-2016'),
 (460000, '01-2016'),
 (455000, '01-2016'),
 (455000, '01-2016'),
 (455000, '01-2016'),
 (455000, '01-2016'),
 (452000, '01-2016'),
 (450000, '01-2016'),
 (450000, '01-2016'),
 (450000, '01-2016'),
 (445000, '01-2016'),
 (445000, '01-2016'),
 (445000, '01-2016'),
 (445000, '01-2016'),
 (440000, '01-2016'),
 (434000, '01-2016'),
 (430000, '01-2016'),
 (430000, '01-2016'),
 (430000, '01-2016'),
 (430000, '01-2016'),
 (425000, '01-2016'),
 (425000, '01-2016'),
 (420000, '01-2016'),
 (420000, '01-2016'),
 (420000, '01-2016'),
 (420000, '01-2016'),
 (420000, '01-2016'),
 (415000, '01-2016'),
 (410000, '01-2016'),
 (410000, '01-2016'),
 (408000, '01-2016'),
 (407000, '01-2016'),
 (405000, '01-2016'),
 (405000, '01-2016'),
 (405000, '01-2016'),
 (400000, '01-2016'),
 (400000, '01-2016'),
 (400000, '01-2016'),
 (400000, '01-2016'),
 (399000, '01-2016'),
 (395000, '01-2016'),
 (395000, '01-2016'),
 (395000, '01-2016'),
 (395000, '01-2016'),
 (390000, '01-2016'),
 (385000, '01-2016'),
 (385000, '01-2016'),
 (384000, '01-2016'),
 (382500, '01-2016'),
 (381000, '01-2016'),
 (380000, '01-2016'),
 (375000, '01-2016'),
 (375000, '01-2016'),
 (374000, '01-2016'),
 (371500, '01-2016'),
 (370000, '01-2016'),
 (370000, '01-2016'),
 (370000, '01-2016'),
 (365444, '01-2016'),
 (360000, '01-2016'),
 (360000, '01-2016'),
 (355000, '01-2016'),
 (355000, '01-2016'),
 (352000, '01-2016'),
 (350000, '01-2016'),
 (350000, '01-2016'),
 (343000, '01-2016'),
 (342000, '01-2016'),
 (340000, '01-2016'),
 (340000, '01-2016'),
 (340000, '01-2016'),
 (330000, '01-2016'),
 (325000, '01-2016'),
 (322000, '01-2016'),
 (312000, '01-2016'),
 (310000, '01-2016'),
 (305000, '01-2016'),
 (305000, '01-2016'),
 (300000, '01-2016'),
 (295000, '01-2016'),
 (290000, '01-2016'),
 (290000, '01-2016'),
 (285000, '01-2016'),
 (280000, '01-2016'),
 (275000, '01-2016'),
 (264000, '01-2016'),
 (255000, '01-2016'),
 (240500, '01-2016'),
 (235000, '01-2016'),
 (220000, '01-2016'),
 (220000, '01-2016'),
 (210000, '01-2016'),
 (207500, '01-2016'),
 (115000, '01-2016'),
 (100000, '01-2016'),
 (2400000, '01-2017'),
 (2300000, '01-2017'),
 (2100000, '01-2017'),
 (2080000, '01-2017'),
 (2000000, '01-2017'),
 (1880000, '01-2017'),
 (1750000, '01-2017'),
 (1700000, '01-2017'),
 (1600000, '01-2017'),
 (1570000, '01-2017'),
 (1497000, '01-2017'),
 (1460000, '01-2017'),
 (1440000, '01-2017'),
 (1405000, '01-2017'),
 (1335000, '01-2017'),
 (1325000, '01-2017'),
 (1287500, '01-2017'),
 (1275000, '01-2017'),
 (1270000, '01-2017'),
 (1250000, '01-2017'),
 (1240000, '01-2017'),
 (1230000, '01-2017'),
 (1220000, '01-2017'),
 (1210000, '01-2017'),
 (1200000, '01-2017'),
 (1170000, '01-2017'),
 (1160000, '01-2017'),
 (1150000, '01-2017'),
 (1150000, '01-2017'),
 (1135000, '01-2017'),
 (1135000, '01-2017'),
 (1100000, '01-2017'),
 (1100000, '01-2017'),
 (1090000, '01-2017'),
 (1065000, '01-2017'),
 (1060000, '01-2017'),
 (1040000, '01-2017'),
 (1030000, '01-2017'),
 (1025000, '01-2017'),
 (975000, '01-2017'),
 (950000, '01-2017'),
 (950000, '01-2017'),
 (950000, '01-2017'),
 (942500, '01-2017'),
 (930000, '01-2017'),
 (925000, '01-2017'),
 (920000, '01-2017'),
 (920000, '01-2017'),
 (910000, '01-2017'),
 (910000, '01-2017'),
 (910000, '01-2017'),
 (910000, '01-2017'),
 (900000, '01-2017'),
 (900000, '01-2017'),
 (900000, '01-2017'),
 (900000, '01-2017'),
 (896000, '01-2017'),
 (895000, '01-2017'),
 (885000, '01-2017'),
 (885000, '01-2017'),
 (873270, '01-2017'),
 (860000, '01-2017'),
 (860000, '01-2017'),
 (855000, '01-2017'),
 (854000, '01-2017'),
 (850000, '01-2017'),
 (849000, '01-2017'),
 (847000, '01-2017'),
 (840000, '01-2017'),
 (830000, '01-2017'),
 (825000, '01-2017'),
 (820000, '01-2017'),
 (820000, '01-2017'),
 (815000, '01-2017'),
 (805000, '01-2017'),
 (805000, '01-2017'),
 (790000, '01-2017'),
 (790000, '01-2017'),
 (790000, '01-2017'),
 (785000, '01-2017'),
 (785000, '01-2017'),
 (782000, '01-2017'),
 (775000, '01-2017'),
 (775000, '01-2017'),
 (775000, '01-2017'),
 (770000, '01-2017'),
 (762000, '01-2017'),
 (760000, '01-2017'),
 (760000, '01-2017'),
 (750000, '01-2017'),
 (750000, '01-2017'),
 (749450, '01-2017'),
 (735000, '01-2017'),
 (735000, '01-2017'),
 (732750, '01-2017'),
 (730000, '01-2017'),
 (730000, '01-2017'),
 (730000, '01-2017'),
 (729000, '01-2017'),
 (722000, '01-2017'),
 (718000, '01-2017'),
 (715000, '01-2017'),
 (715000, '01-2017'),
 (710000, '01-2017'),
 (700000, '01-2017'),
 (695000, '01-2017'),
 (685000, '01-2017'),
 (680000, '01-2017'),
 (679000, '01-2017'),
 (676000, '01-2017'),
 (672000, '01-2017'),
 (670000, '01-2017'),
 (665000, '01-2017'),
 (660000, '01-2017'),
 (660000, '01-2017'),
 (658000, '01-2017'),
 (651000, '01-2017'),
 (650000, '01-2017'),
 (645000, '01-2017'),
 (640000, '01-2017'),
 (640000, '01-2017'),
 (635000, '01-2017'),
 (635000, '01-2017'),
 (630000, '01-2017'),
 (630000, '01-2017'),
 (630000, '01-2017'),
 (620000, '01-2017'),
 (620000, '01-2017'),
 (620000, '01-2017'),
 (617500, '01-2017'),
 (610000, '01-2017'),
 (602500, '01-2017'),
 (600000, '01-2017'),
 (595000, '01-2017'),
 (595000, '01-2017'),
 (595000, '01-2017'),
 (590000, '01-2017'),
 (590000, '01-2017'),
 (585000, '01-2017'),
 (583000, '01-2017'),
 (580000, '01-2017'),
 (580000, '01-2017'),
 (580000, '01-2017'),
 (576500, '01-2017'),
 (576500, '01-2017'),
 (576000, '01-2017'),
 (576000, '01-2017'),
 (575000, '01-2017'),
 (575000, '01-2017'),
 (575000, '01-2017'),
 (575000, '01-2017'),
 (575000, '01-2017'),
 (574000, '01-2017'),
 (572000, '01-2017'),
 (570000, '01-2017'),
 (570000, '01-2017'),
 (570000, '01-2017'),
 (570000, '01-2017'),
 (565000, '01-2017'),
 (557000, '01-2017'),
 (556000, '01-2017'),
 (555000, '01-2017'),
 (555000, '01-2017'),
 (550000, '01-2017'),
 (550000, '01-2017'),
 (550000, '01-2017'),
 (550000, '01-2017'),
 (550000, '01-2017'),
 (543000, '01-2017'),
 (540000, '01-2017'),
 (537000, '01-2017'),
 (530000, '01-2017'),
 (530000, '01-2017'),
 (530000, '01-2017'),
 (527000, '01-2017'),
 (525000, '01-2017'),
 (522500, '01-2017'),
 (522000, '01-2017'),
 (516000, '01-2017'),
 (515000, '01-2017'),
 (510000, '01-2017'),
 (510000, '01-2017'),
 (510000, '01-2017'),
 (510000, '01-2017'),
 (510000, '01-2017'),
 (510000, '01-2017'),
 (507000, '01-2017'),
 (505000, '01-2017'),
 (505000, '01-2017'),
 (505000, '01-2017'),
 (500000, '01-2017'),
 (500000, '01-2017'),
 (500000, '01-2017'),
 (490000, '01-2017'),
 (490000, '01-2017'),
 (490000, '01-2017'),
 (487000, '01-2017'),
 (486000, '01-2017'),
 (485000, '01-2017'),
 (485000, '01-2017'),
 (485000, '01-2017'),
 (484000, '01-2017'),
 (480000, '01-2017'),
 (480000, '01-2017'),
 (480000, '01-2017'),
 (480000, '01-2017'),
 (476000, '01-2017'),
 (475500, '01-2017'),
 (475000, '01-2017'),
 (475000, '01-2017'),
 (474000, '01-2017'),
 (470000, '01-2017'),
 (470000, '01-2017'),
 (470000, '01-2017'),
 (470000, '01-2017'),
 (469000, '01-2017'),
 (465000, '01-2017'),
 (465000, '01-2017'),
 (465000, '01-2017'),
 (460000, '01-2017'),
 (460000, '01-2017'),
 (460000, '01-2017'),
 (460000, '01-2017'),
 (459000, '01-2017'),
 (458000, '01-2017'),
 (455000, '01-2017'),
 (455000, '01-2017'),
 (455000, '01-2017'),
 (452500, '01-2017'),
 (450000, '01-2017'),
 (450000, '01-2017'),
 (450000, '01-2017'),
 (450000, '01-2017'),
 (450000, '01-2017'),
 (450000, '01-2017'),
 (445000, '01-2017'),
 (445000, '01-2017'),
 (440000, '01-2017'),
 (440000, '01-2017'),

In [9]:
results = session.query(Housing.SUBURB, func.round(func.avg(Housing.PRICE),2))\
        .group_by(Housing.SUBURB)\
        .limit(200)\
        .all()
results

[('Alexander Heights', 453285.16),
 ('Alfred Cove', 840086.57),
 ('Alkimos', 413749.81),
 ('Anketell', 1085769.23),
 ('Applecross', 1376689.87),
 ('Ardross', 1072145.32),
 ('Armadale', 246611.11),
 ('Ascot', 803359.17),
 ('Ashby', 483321.63),
 ('Ashfield', 502297.41),
 ('Attadale', 1192734.71),
 ('Atwell', 542581.78),
 ('Aubin Grove', 570786.52),
 ('Aveley', 440986.49),
 ('Balcatta', 524628.17),
 ('Baldivis', 419363.43),
 ('Balga', 309362.07),
 ('Ballajura', 420807.38),
 ('Banjup', 1103590.25),
 ('Banksia Grove', 382368.07),
 ('Baskerville', 1214545.45),
 ('Bassendean', 546484.16),
 ('Bateman', 801316.95),
 ('Bayswater', 607954.56),
 ('Beaconsfield', 774403.95),
 ('Beckenham', 405862.69),
 ('Bedford', 660490.06),
 ('Bedfordale', 748650.23),
 ('Beechboro', 385165.42),
 ('Beeliar', 536281.17),
 ('Beldon', 490010.56),
 ('Belhus', 961562.5),
 ('Bellevue', 368800.37),
 ('Belmont', 505116.59),
 ('Bennett Springs', 495591.73),
 ('Bentley', 457648.77),
 ('Bertram', 381613.42),
 ('Bibra Lake', 544325.85),
 ('Bickley', 897970.59),
 ('Bicton', 1083594.38),
 ('Booragoon', 893440.22),
 ('Boya', 575496.55),
 ('Brabham', 432820.65),
 ('Brentwood', 742031.25),
 ('Brigadoon', 809387.95),
 ('Brookdale', 301784.14),
 ('Bull Creek', 810097.7),
 ('Bullsbrook', 498796.75),
 ('Burns Beach', 898548.32),
 ('Burswood', 975228.57),
 ('Butler', 383239.13),
 ('Byford', 423198.36),
 ('Calista', 293788.89),
 ('Camillo', 300934.62),
 ('Canning Vale', 589988.38),
 ('Cannington', 430695.0),
 ('Carabooda', 1084107.14),
 ('Cardup', 720422.41),
 ('Carine', 805571.85),
 ('Carlisle', 543074.36),
 ('Carmel', 788928.57),
 ('Carramar', 524224.86),
 ('Casuarina', 788188.07),
 ('Caversham', 486736.11),
 ('Champion Lakes', 429918.03),
 ('Chidlow', 508925.48),
 ('Churchlands', 1313734.85),
 ('City Beach', 1654765.27),
 ('Claremont', 1282131.56),
 ('Clarkson', 374551.96),
 ('Cloverdale', 438314.29),
 ('Cockburn Central', 492742.42),
 ('Como', 977760.83),
 ('Connolly', 705674.0),
 ('Coogee', 790131.3),
 ('Coolbellup', 477543.48),
 ('Coolbinia', 1162713.64),
 ('Cooloongup', 287516.29),
 ('Cottesloe', 1646283.33),
 ('Craigie', 448367.02),
 ('Crawley', 943272.73),
 ('Currambine', 543432.58),
 ('Daglish', 1051835.62),
 ('Dalkeith', 1951092.34),
 ('Darch', 574450.44),
 ('Darling Downs', 843106.06),
 ('Darlington', 707432.69),
 ('Dayton', 464128.38),
 ('Dianella', 678584.46),
 ('Doubleview', 836239.58),
 ('Duncraig', 713762.37),
 ('East Cannington', 507159.25),
 ('East Fremantle', 1122097.5),
 ('East Perth', 510181.82),
 ('East Victoria Park', 651532.45),
 ('Eden Hill', 467236.73),
 ('Edgewater', 560366.25),
 ('Eglinton', 391879.74),
 ('Ellenbrook', 388606.45),
 ('Embleton', 524185.86),
 ('Ferndale', 460006.25),
 ('Floreat', 1476393.7),
 ('Forrestdale', 665153.27),
 ('Forrestfield', 420805.08),
 ('Fremantle', 859845.07),
 ('Gidgegannup', 792695.4),
 ('Girrawheen', 318997.87),
 ('Glen Forrest', 631721.58),
 ('Glendalough', 480360.0),
 ('Gnangara', 1158358.97),
 ('Golden Bay', 415339.51),
 ('Gooseberry Hill', 857120.44),
 ('Gosnells', 299551.72),
 ('Greenmount', 514081.52),
 ('Greenwood', 512138.66),
 ('Guildford', 750958.86),
 ('Gwelup', 863702.19),
 ('Hamersley', 560256.65),
 ('Hamilton Hill', 500102.56),
 ('Hammond Park', 528643.68),
 ('Harrisdale', 546854.44),
 ('Haynes', 240865.74),
 ('Hazelmere', 595263.16),
 ('Heathridge', 463023.83),
 ('Helena Valley', 609165.68),
 ('Henley Brook', 615389.2),
 ('Herne Hill', 616636.51),
 ('High Wycombe', 435423.78),
 ('Highgate', 790883.03),
 ('Hilbert', 463561.36),
 ('Hillarys', 930758.45),
 ('Hillman', 309421.64),
 ('Hilton', 555069.39),
 ('Hocking', 500639.34),
 ('Hope Valley', 785000.0),
 ('Hopeland', 809750.0),
 ('Hovea', 831857.14),
 ('Huntingdale', 400517.51),
 ('Iluka', 894611.79),
 ('Inglewood', 824133.91),
 ('Innaloo', 552731.47),
 ('Jandabup', 1069666.67),
 ('Jandakot', 737267.39),
 ('Jane Brook', 506568.16),
 ('Jarrahdale', 549115.45),
 ('Jindalee', 610807.34),
 ('Jolimont', 1057174.53),
 ('Joondalup', 521552.87),
 ('Joondanna', 624365.66),
 ('Kalamunda', 679729.41),
 ('Kallaroo', 813718.75),
 ('Karawara', 710167.75),
 ('Kardinya', 667850.67),
 ('Karnup', 609758.6),
 ('Karragullen', 598593.75),
 ('Karrinyup', 959109.91),
 ('Kelmscott', 371619.47),
 ('Kensington', 929288.27),
 ('Kenwick', 397629.51),
 ('Kewdale', 515815.29),
 ('Keysbrook', 1027000.0),
 ('Kiara', 439100.92),
 ('Kingsley', 583094.12),
 ('Kinross', 500355.17),
 ('Koondoola', 385320.11),
 ('Koongamia', 332594.29),
 ('Kwinana Town Centre', 185598.32),
 ('Landsdale', 551263.28),
 ('Langford', 409908.45),
 ('Lathlain', 726986.11),
 ('Leda', 337275.15),
 ('Leederville', 859113.64),
 ('Leeming', 711187.38),
 ('Lesmurdie', 671163.87),
 ('Lockridge', 354943.01),
 ('Lynwood', 428731.43),
 ('Maddington', 344360.47),
 ('Madeley', 588321.9),
 ('Mahogany Creek', 612211.54),
 ('Maida Vale', 589742.78),
 ('Manning', 839030.22),
 ('Marangaroo', 415592.44),
 ('Mardella', 771208.33),
 ('Mariginiup', 1141234.04),
 ('Marmion', 1014024.82),
 ('Martin', 557350.75),
 ('Maylands', 739668.92),
 ('Medina', 271981.13),
 ('Melville', 795250.0),
 ('Menora', 1193894.74),
 ('Merriwa', 333189.27),
 ('Middle Swan', 410416.9),
 ('Midland', 423032.79),
 ('Midvale', 357054.62),
 ('Millendon', 954187.5),
 ('Mindarie', 725433.49),
 ('Mirrabooka', 399135.41),
 ('Morley', 462455.22),
 ('Mosman Park', 1398858.91),
 ('Mount Claremont', 1279029.73)]

In [14]:
active_suburbs = session.query(Housing.SUBURB, func.count(Housing.SUBURB)).order_by(func.count(Housing.SUBURB).desc()).group_by(Housing.SUBURB).limit(100).all()
active_suburbs

[('Bertram', 231),
 ('Iluka', 212),
 ('Bennett Springs', 211),
 ('Mindarie', 209),
 ('Carramar', 208),
 ('Butler', 207),
 ('Merriwa', 206),
 ('Henley Brook', 204),
 ('Jane Brook', 201),
 ('Darch', 201),
 ('Tapping', 198),
 ('Secret Harbour', 197),
 ('Atwell', 195),
 ('Wattle Grove', 188),
 ('Ridgewood', 186),
 ('Port Kennedy', 186),
 ('Huntingdale', 185),
 ('Hocking', 183),
 ('Gwelup', 183),
 ('South Guildford', 182),
 ('Maida Vale', 180),
 ('Jandakot', 180),
 ('Currambine', 178),
 ('Ashby', 178),
 ('Stratton', 177),
 ('Sinagra', 172),
 ('Clarkson', 170),
 ('Helena Valley', 169),
 ('Banksia Grove', 166),
 ('Madeley', 165),
 ('High Wycombe', 164),
 ('Quinns Rocks', 162),
 ('Beeliar', 162),
 ('Aubin Grove', 162),
 ('The Vines', 160),
 ('Singleton', 160),
 ('Landsdale', 158),
 ('Guildford', 158),
 ('Mount Helena', 157),
 ('City Beach', 156),
 ('Canning Vale', 156),
 ('Ellenbrook', 155),
 ('Warnbro', 154),
 ('Beldon', 153),
 ('South Lake', 152),
 ('Redcliffe', 151),
 ('Manning', 151),
 ('Lockridge', 151),
 ('Kenwick', 150),
 ('Harrisdale', 149),
 ('Middle Swan', 148),
 ('Aveley', 148),
 ('Pearsall', 146),
 ('Kensington', 146),
 ('Stirling', 145),
 ('Parkerville', 145),
 ('Orelia', 145),
 ('Kinross', 145),
 ('Kallaroo', 144),
 ('Caversham', 144),
 ('Salter Point', 143),
 ('Koondoola', 143),
 ('Langford', 142),
 ('Hillarys', 142),
 ('Brookdale', 142),
 ('Marmion', 141),
 ('Wanneroo', 139),
 ('Stoneville', 139),
 ('Mirrabooka', 139),
 ('Glen Forrest', 139),
 ('Waikiki', 138),
 ('Greenmount', 138),
 ('Ballajura', 138),
 ('Gooseberry Hill', 137),
 ('Trigg', 136),
 ('Brentwood', 136),
 ('Mundaring', 135),
 ('Mount Nasura', 135),
 ('Mount Claremont', 135),
 ('Calista', 135),
 ('Mullaloo', 134),
 ('Hillman', 134),
 ('Bibra Lake', 134),
 ('Southern River', 133),
 ('Yangebup', 132),
 ('Cooloongup', 132),
 ('Churchlands', 132),
 ('Burns Beach', 132),
 ('Mount Richon', 131),
 ('Coogee', 131),
 ('Warwick', 130),
 ('Darlington', 130),
 ('Camillo', 130),
 ('Heathridge', 128),
 ('Bedfordale', 128),
 ('Alexander Heights', 128),
 ('Floreat', 127),
 ('Swanbourne', 125),
 ('Connolly', 125),
 ('Champion Lakes', 122)]

In [20]:
session.query(func.min(Housing.PRICE), func.max(Housing.PRICE)).all()

[(51000, 2440000)]

In [15]:
suburb = 'Bertram'
session.query(func.min(Housing.PRICE), func.max(Housing.PRICE)).filter(Housing.SUBURB == suburb).all()

[(152000, 567000)]